config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books do
    collection do
      get :recent
      get :completed
      get :short
    end
  end

  resources :chapters do
    resources :comments
  end

  get '/users/adfree', to: 'users#adfree'
  resources :users do
    member do
      get :follow, to: 'users#follow'
      get :unfollow, to: 'users#unfollow'
    end
  end

  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'

  root 'books#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :chapters
  has_many :comments
  attr_accessor :login
  acts_as_followable
  acts_as_follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = @user.following_users

    @books =  Book.where(user_id: params[:id]).order("created_at DESC")
  end

  def your_stories
    @selections =  Book.where(user_id: params[:id]).order("created_at DESC")
  end

  def adfree
    # @user = User.find(current_user.id)
  end

  def follow
    @followable = User.find(params[:id])
    current_user.follow(@followable)
    redirect_to :back
  end

  def unfollow
    @followable = User.find(params[:id])
    current_user.stop_following(@followable)
    redirect_to :back
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/adfree.html.erb
<div class="container">
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <h1>Go adfree! Coming soon.</h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <p>Unfortunately this feature is not availible, however I'm planning on adding a low-cost subscription feature where you'll be able to view these pages without ads as well as download ebooks as an .epub to read off of the website!  It will occur after I add ads, as at the time of writing this they are still not implemented.</p>
      <p>If you have any comments to add, don't be afraid to let us know!  And you can read more about our future plans <%= link_to "in our about page", about_path %></p>
      <%= link_to "Return to the homepage", root_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="three columns nav-plug"></div>
    <div class="nine columns">
      <h1><%= @user.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">
      <ul class="nav-items">
        <%= link_to content_tag(:li, "Home", class: 'nav-item'), root_path, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "Edit", class: 'nav-item'), edit_user_registration_path, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "New Book", class: 'nav-item'), new_book_path, class: "nav-item-link" %>
        <% @users.each do |user| %>
          <%= link_to content_tag(:li, "#{user.name}", class: 'nav-item'), user_path(user), class: "nav-item-link" %>
        <% end %>
      </ul>
    </div>
    <div class="nine columns">
      <p><%= @user.description %></p> <!-- Add markdown! -->
      <% unless current_user.nil? || current_user.id == @user.id %>
        <% if @user.followed_by?(current_user) %>
          <h5><%= link_to "Unfollow", unfollow_user_path(@user) %></h5>
        <% else %>
          <h5><%= link_to "Follow", follow_user_path(@user) %></h5>
        <% end %>
      <% end %>
      <h3>Stories</h3>
      <% unless @books.empty? %>
        <% @books.each do |book| %>
          <p>
            <%= link_to "#{book.title}", book_path(book) %>
            <%= ", #{book.created_at.month}/#{book.created_at.day}/#{book.created_at.year} | #{book.description}" %>
            <% if user_signed_in? %>
              <% if current_user.id == book.user_id %>
                <%= link_to " - edit", edit_book_path(book) %>
              <% end %>
            <% end %>
          </p>
        <% end %>
      <% else %>
        <p>You've never posted any stories.  <% link_to "Create one.", new_book_path %></p>
      <% end %>
    </div>
  </div>
</div>