config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books do
    collection do
      get :recent
      get :completed
      get :short
    end
  end

  resources :chapters do
    resources :comments
  end

  get '/users/adfree', to: 'users#adfree'
  resources :users do
    member do
      get :follow, to: 'users#follow'
      get :unfollow, to: 'users#unfollow'
    end
  end

  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'

  root 'books#index'

end

app/models/book.rb
# require 'elasticsearch/model'

class Book < ActiveRecord::Base
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  searchkick
  Book.reindex
  has_many :chapters
  belongs_to :user
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true
  validates :title, :user_id, presence: true # add user_id later on

  scope :recent,    ->{ order("created_at DESC") }
  scope :completed, ->{ where(complete: true) }
  scope :short,     ->{ where("volumes <= 4") }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_chapters, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:query].present?
      @books = Book.search(params[:query],
        page: params[:page], per_page: 10,
        fields: [:title, :description, :content]
      )
    else
      @books = Book.all.paginate(:page => params[:page], per_page: 10)
    end

    @route_with_scope = books_path
  end

  # GET /books/recent
  def recent
    # @books = Book.recent.paginate(:page => params[:page], per_page: 15)
    if params[:query].present?
      @books = Book.recent.search(params[:query],
        page: params[:page], per_page: 10,
        fields: [:title, :description, :content]
      )
    else
      @books = Book.recent.paginate(:page => params[:page], per_page: 10)
    end

    @route_with_scope = recent_books_path
    render 'index'
  end

  # GET /books/completed
  def completed
    # @books = Book.completed.paginate(:page => params[:page], per_page: 15)
    if params[:query].present?
      @books = Book.completed.search(params[:query],
        page: params[:page], per_page: 10,
        fields: [:title, :description, :content]
      )
    else
      @books = Book.completed.paginate(:page => params[:page], per_page: 10)
    end

    @route_with_scope = completed_books_path
    render 'index'
  end

  # GET /books/short
  def short
    # @books = Book.short.paginate(:page => params[:page], per_page: 15)
    if params[:query].present?
      @books = Book.short.search(params[:query],
        page: params[:page], per_page: 10,
        fields: [:title, :description, :content]
      )
    else
      @books = Book.short.paginate(:page => params[:page], per_page: 10)
    end

    @route_with_scope = short_books_path
    render 'index'
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    if user_signed_in?
      @book = Book.new
    else
      flash[:failure] = "You must be signed up to make a post.  Create an account now!"
      redirect_to new_user_registration_path
    end
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    # params[:book][:chapters_attributes][:user_id] = 6
    @book = current_user.books.build(book_params)

    if @book.save
      update_volumes_count
      update_tags
      flash[:success] = "This book was successfully created."
      redirect_to @book
    else
      flash["failure"] = "There was a problem creating your book."
      render 'new'
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      update_volumes_count
      update_tags
      flash[:success] = "Book was successfully updated."
      redirect_to @book
    else
      flash[:failure] = "There was a problem updating your book."
      render 'edit'
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy

    flash[:success] = "This book was successfully deleted."
    redirect_to books_url
    # respond_to do |format|
    #   format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_chapters
      @chapters = Chapter.all.where(book_id: @book)
    end

    def update_volumes_count
      @book.update_attributes(volumes: Chapter.all.where(book_id: @book).count)
    end

    def update_tags
      set_chapters
      book_tags = ""
      # we'll take all the tags from chapters and add to book_tag
      @chapters.each do |chapter|
        if book_tags.empty?
          book_tags = chapter.tags
        else
          tags = chapter.tags.split(', ')
          tags.each do |tag|
            # checks if book_tags contains tag, case insensitive
            unless book_tags =~ /#{tag}/i
              book_tags = book_tags + ", " + tag
            end
          end
          # book_tags = book_tags + ", " + chapter.tags
        end
      end
      @book.update_attributes(tags: book_tags)
    end

    def authorized_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to books_path, notice: "Not authorized to edit this nook" if @book.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :complete, :volumes, :user_id, chapters_attributes: [:id, :user_id, :title, :description, :tags, :content, :_destroy])
    end
end

# Search not using elasticsearch, pure sql
# subject to sql injection, etc
# if params[:query].present?
#   @items = params[:query].split(' ') # array of search items
#   sql_query = "" # set up sql query
#
#   @items.each do |item| # set up to search each word
#     sql_query = sql_query + "(title LIKE \"%#{item}%\" OR description LIKE \"%#{item}%\" OR tags LIKE \"%#{item}%\") AND "
#   end
#
#   sql_query = sql_query.chomp(' AND ') # remove extra AND
#   # actually search database for list
#   @books = Book.all.where(sql_query).paginate(:page => params[:page], per_page: 10)
# else
#   @books = Book.all.paginate(:page => params[:page], per_page: 10)
# end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_chapter_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-text-field" %>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-text-field" %>
    <%= f.label :tags %>
    <%= f.text_field :tags, class: "form-text-field" %>
    <%= f.label :content %>
    <%= f.text_area :content, class: "content-text-area" %>
  </div>
  <%= link_to_remove_association "Remove Chapter", f %>
</div>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-text-field" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-text-field" %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div id="chapters">
    <%= f.fields_for :chapters do |chapter| %>
      <%= render 'chapter_fields', f: chapter %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add chapter', f, :chapters %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <h1>Editing <%= @book.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">
      <ul class="nav-items">
        <%= link_to content_tag(:li, "Cancel", class: 'nav-item'), book_path(@book), class: 'nav-item-link' %>
      </ul>
    </div>
    <div class="nine columns">
      <%= render 'form' %>
    </div>
    <!-- <h6>Delete this book</h6>
    <p>Are you sure you would like to delete this book?  Once done it cannot be deleted, and you will lose any hit counts/information about the book.</p> -->
    <!-- link_to "Delete #{@book.title}"  -->
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <h1>Read and post stories!</h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">
      <ul class="nav-items">
        <%= link_to content_tag(:li, "Publish a book", class: 'nav-item'), new_book_path, class: 'nav-item-link' %>
        <div><%= content_tag(:li, "Only search for:", class: 'nav-item') %></div>
        <%= link_to content_tag(:li, "All", class: 'nav-item'), books_path, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "Completed", class: 'nav-item'), completed_books_path, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "Short", class: 'nav-item'), short_books_path, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "Recent", class: 'nav-item'), recent_books_path, class: "nav-item-link" %>
      </ul>
    </div>
    <div class="nine columns">

      <%= form_tag @route_with_scope, method: :get do %>
        <p>
          <%= text_field_tag :query, params[:query] %>
          <%= submit_tag "search", name: nil %>
        </p>
      <% end %>

      <% if params[:query].nil? %>
        <p>Welcome to ____, where you can read and write stories for anyone to read!  Get started by <%= link_to "signing up", new_user_registration_path %>, <%= link_to "posting a story", new_book_path %> or searching above.</p>
      <% end %>
        <!-- <p> "Your search for #{params[:query]} returned #{@books.count} results" </p> -->
       <!-- end  -->

      <% unless @books.empty? %>
        <% @books.each do |book| %>
          <div class="book-wrapper">
            <%= link_to User.find(book.user_id).name, user_path(book.user_id) %>
            <!-- link_to content_tag(:p, "#{book.title} | #{book.description} [#{book.tags}]"), book_path(book), class: 'book-list-item' -->
            <a href="<%= book_path(book) %>" class="book-list-item">
              <p class="tooltip">
                <%= "#{book.title} | #{book.description}" %>
                <span class="tooltiptext"><%= book.tags %></span>
              </p>
            </a>
          </div>
        <% end %>
      <% else %>
        <p>Unfortunately there were no search results.  We'd recommend reducing the specificity of your search or writing and <%= link_to "publishing the book", new_book_path %> yourself!</p>
      <% end %>
      <div class="pagination">
        <%= will_paginate @books %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <h1>Publish a book</h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">
      <ul class="nav-items">
        <%= link_to content_tag(:li, "Home", class: 'nav-item'), books_path, class: 'nav-item-link' %>
        <%= link_to content_tag(:li, current_user.name, class: 'nav-item'), user_path(current_user.id), class: 'nav-item-link' %>
      </ul>
    </div>
    <div class="nine columns">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="three columns">&nbsp;</div>
    <div class="nine columns">
      <h1><%= "#{@book.title} | #{@book.volumes} chapters" %></h1>
    </div>
  </div>
  <div class="row">
    <div class="three columns">
      <ul class="nav-items">
        <%= link_to content_tag(:li, "Home", class: 'nav-item'), books_path, class: 'nav-item-link' %>
        <%= link_to content_tag(:li, User.find(@book.user_id).name, class: 'nav-item'), user_path(@book.user_id), class: 'nav-item-link' %>
        <% if user_signed_in? && current_user.id == @book.user_id %>
          <%= link_to content_tag(:li, "Edit", class: 'nav-item'), edit_book_path(@book), class: 'nav-item-link' %>
        <% end %>
        <%= link_to content_tag(:li, "Publish a book", class: 'nav-item'), new_book_path, class: 'nav-item-link' %>
      </ul>
    </div>
    <div class="nine columns">
      <p><%= @book.description %></p>
      <% unless @chapters.empty? %>
        <% @chapters.each do |chapter| %>
          <div class="book-wrapper no-tool-tip">
            <%= link_to content_tag(:p, "#{chapter.title} | #{chapter.description} [#{chapter.tags}]"), chapter_path(chapter), class: 'book-list-item' %>
          </div>
        <% end %>
      <% else %>
        <p>Unfortunately it looks as though there are no chapters in this book.</p>
        <% if user_signed_in? && current_user.id == @book.user_id %>
          <p>If you own this book you may further edit it <%= link_to "here", edit_book_path(@book) %></p>
        <% end %>
      <% end %>
      <div class="pagination">
      </div>
    </div>
  </div>
</div>