config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books do
    collection do
      get :recent
      get :completed
      get :short
    end
  end

  resources :chapters do
    resources :comments
  end

  get '/users/adfree', to: 'users#adfree'
  resources :users do
    member do
      get :follow, to: 'users#follow'
      get :unfollow, to: 'users#unfollow'
    end
  end

  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'

  root 'books#index'

end

app/views/layouts/_footer.html.erb
<footer class="row footer">
	<div class="twelve columns">
		<p class="small-plug-footer">Copyright 2017 | <%= link_to "Contact Us", contact_path %></p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="row header">
  <div class="ten columns alert">&nbsp;</div>
  <div class="two columns">
    <ul class="nav-items header-nav">
      <% if user_signed_in? %>
        <%= link_to content_tag(:li, "sign out", class: 'nav-item'), destroy_user_session_path, :method => :delete, class: "nav-item-link" %>
        <%= link_to content_tag(:li, "ad free", class: 'nav-item'), users_adfree_path(current_user) %>
        <%= link_to content_tag(:li, "#{current_user.name}", class: 'nav-item'), user_path(current_user) %>
      <% else %>
        <%= link_to "sign in", new_user_session_path %>
        <%= link_to "sign up", new_user_registration_path %>
      <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="twelve columns alert">
      <% flash.each do |key, msg| %>
        <%= content_tag(:h5, msg, class: "alert-#{key}") %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reading</title>
  <%= stylesheet_link_tag    'skeleton', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Noto+Serif|Nunito+Sans:300,400" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>